server:
  port: 8081

spring:
  application:
    name: COMPANY-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/teleradiology
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      uri: http://localhost:8888
