spring:
  application:
    name: COMMON-LIB


  data:
    redis:
      host: localhost
      port: 6379


springdoc:
  api-docs:
    version: openapi_3_0
    groups:
      enabled: true
    path: /swagger-ui.html
